In [16]:
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt
import plotly.express as px

In [6]:
def d2_acc2(h, x):
        # Once again, we create the second derivative matrix
        size = len(x)
        offDiag = np.zeros(size)
        offDiag[1] = 1
        
        H = -1*(-2*np.identity(size) + linalg.toeplitz(offDiag))/h**2
        return H

[[ 200. -100.   -0. ...   -0.   -0.   -0.]
 [-100.  200. -100. ...   -0.   -0.   -0.]
 [  -0. -100.  200. ...   -0.   -0.   -0.]
 ...
 [  -0.   -0.   -0. ...  200. -100.   -0.]
 [  -0.   -0.   -0. ... -100.  200. -100.]
 [  -0.   -0.   -0. ...   -0. -100.  200.]]


In [7]:
def d2_acc4(xgrid):
    N = len(xgrid)
    dx = xgrid[1] - xgrid[0]

    # Generate the matrix for the second derivative using a five-point stencil
    main_diag = np.ones(N) * (-5.0 / 2 / dx**2)
    off_diag = np.ones(N - 1) * 4 / 3 / dx**2
    off_diag2 = np.ones(N - 2) * (-1.0 / (12 * dx**2))

    D2 = np.diag(main_diag) + np.diag(off_diag, k=1) + np.diag(
      off_diag, k=-1) + np.diag(off_diag2, k=2) + np.diag(off_diag2, k=-2)
    
    return D2

[[-250.          133.33333333   -8.33333333 ...    0.
     0.            0.        ]
 [ 133.33333333 -250.          133.33333333 ...    0.
     0.            0.        ]
 [  -8.33333333  133.33333333 -250.         ...    0.
     0.            0.        ]
 ...
 [   0.            0.            0.         ... -250.
   133.33333333   -8.33333333]
 [   0.            0.            0.         ...  133.33333333
  -250.          133.33333333]
 [   0.            0.            0.         ...   -8.33333333
   133.33333333 -250.        ]]


In [22]:
def d2_acc6(xgrid):
    N = len(xgrid)
    dx = xgrid[1] - xgrid[0]

    # Generate the matrix for the second derivative using a five-point stencil
    main_diag = np.ones(N) * (-49.0 / 18 / dx**2)
    off_diag = np.ones(N - 1) * 3.0 / 2 / dx**2
    off_diag2 = np.ones(N - 2) * (-3.0 / (20 * dx**2))
    off_diag3 = np.ones(N - 3) * (1 / 90 / dx**2)

    D2 = np.diag(main_diag) + np.diag(off_diag, k=1) + np.diag(
      off_diag, k=-1) + np.diag(off_diag2, k=2) + np.diag(off_diag2, k=-2) + np.diag(off_diag3, k = 3) + np.diag(off_diag3, k = -3)
    
    return D2

In [23]:
x_max = 10.0
h = 10**-1
x = np.arange(-x_max, x_max + h, h)
print(len(x))
matrix = d2_acc6(x)

fig = px.imshow(matrix, color_continuous_scale="Viridis")
fig.show()

201
